[package]
name = "whisp"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
argh = "0.1.10"
pest = "2.7.1"
pest_derive = { version = "2.7.1", features = ["grammar-extras"] }
thiserror = "1.0.40"
