program = _{
  SOI ~ 
  function_declaration* ~ 
  EOI
}

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
RESERVED = _{";" | "{" | "}" | "\""}

function_declaration = {
  (visibility_modifier ~ WHITESPACE+)? ~
  "fn" ~ WHITESPACE+ ~
  identifier ~
  formal_parameters ~
  statement_block
}

visibility_modifier = @{ "pub" }

identifier = @{ (ASCII_ALPHANUMERIC | "_")+ }

formal_parameters = { "(" ~ ")" }

statement_block = {
  "{" ~ (statement ~ ";")* ~ statement? ~ "}"
}

statement = {
  lexical_declaration | function_call 
}

lexical_declaration = {
  "let" ~ WHITESPACE+ ~ identifier ~ "=" ~ statement
}

function_call = {
  (identifier ~ argument*)
}

argument = {
  string | identifier | statement_block
}

string = @{ quoted_string | unquoted_string | raw_quoted_string }
unquoted_string = _{ (!(RESERVED | WHITESPACE) ~ ANY)+ }
quoted_string = _{ ("\"" ~ (!("\"") ~ ANY)* ~ "\"") }
raw_quoted_string = _{ "r#\"" ~ (!("\"#") ~ ANY)* ~ "\"#"}
