program = _{
  SOI ~ 
  function_declaration* ~ 
  EOI
}

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
RESERVED = _{";" | "{" | "}" | "\""}

function_declaration = {
  (visibility_modifier ~ WHITESPACE+)? ~
  "fn" ~ WHITESPACE+ ~
  identifier ~
  formal_parameters ~
  statement_block
}

visibility_modifier = @{ "pub" }

identifier = @{ (ASCII_ALPHANUMERIC | "_")+ }

formal_parameters = { "(" ~ ")" }

statement_block = {
  "{" ~ (statement ~ ";")* ~ statement? ~ "}"
}

statement = {
  lexical_declaration | function_call 
}

lexical_declaration = {
  "let" ~ WHITESPACE+ ~ identifier ~ "=" ~ statement
}

function_call = {
  (identifier ~ argument*)
}

argument = {
  string | identifier | statement_block
}

string = ${ quoted_string_block | raw_quoted_string_block | unquoted_string }
quoted_string_block = _{ ("\"" ~ quoted_string ~ "\"") }
quoted_string = { (!("\"") ~ ANY)* }
raw_quoted_string_block = _{ "r#\"" ~ raw_quoted_string ~ "\"#"}
raw_quoted_string = { (!("\"#") ~ ANY)* }
unquoted_string = { (!(RESERVED | WHITESPACE) ~ ANY)+ }
